version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -w 3 -b 0.0.0.0:8000 stevebrownlee.wsgi"
    volumes:
      - .:/code
    expose:
      - "8000"

